In [80]:
import sys
import numpy as np

In [81]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [82]:
a = np.array([1,2,3,4])

In [83]:
b= np.array([0,.5,1,1.5,2])

In [84]:
a

array([1, 2, 3, 4])

In [85]:
a.dtype

dtype('int32')

In [86]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [87]:
b.dtype

dtype('float64')

In [88]:
np.array([1,2,3,4], dtype=float)

array([1., 2., 3., 4.])

In [89]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [90]:
A.shape

(2, 3)

In [91]:
A.ndim

2

In [92]:
A.size

6

In [93]:
B = np.array([
    [ 
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [94]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [95]:
B.shape

(2, 2, 3)

In [96]:
B.ndim

3

In [97]:
B.size

12

In [98]:
C = np.array([
    [
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4],
    ]
])

C:\Users\Amar\AppData\Local\Temp\ipykernel_15684\3870057742.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [99]:
C.dtype

dtype('O')

In [100]:
C.shape

(2,)

In [101]:
C.size

2

In [102]:
type(C[0])

list

In [103]:
A = np.array([
#. 0. 1. 2  - index positions for our slicing
    [1,2,3], #0
    [4,5,6], #1
    [7,8,9] #2
])

In [104]:
A[1]

array([4, 5, 6])

In [105]:
A[1][0] #selecting the second row and the first element

4

In [106]:
A[1, 0] 
#using the multi dimension selection of NumPy to do what code [44] does
#multi dimension selectors of NumPy [ d1, d2, d3, d4 ..]
#[R,C]
        

4

In [107]:
A[0:2] #selecting everything from d1 which is rows and the selector selects from rows 0 to 1

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
A[:, :2] #selecting every row and selecting from column level elements from 0 to 2

array([[1, 2],
       [4, 5],
       [7, 8]])

In [109]:
A[:2, :2] #selecting the 2 rows 0 and 1 and the same column 

array([[1, 2],
       [4, 5]])

In [110]:
A[:2, 2:] #selecting the last column and 2 rows

array([[3],
       [6]])

In [111]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
A[2] = 99 # expand operation which assigns 99 to row 2

In [114]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])
A[:, :2]

array([['a', 'b'],
       ['d', 'e'],
       ['g', 'h']], dtype='<U1')

In [ ]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

In [115]:
A[:, :2]

array([['a', 'b'],
       ['d', 'e'],
       ['g', 'h']], dtype='<U1')

In [140]:
a.sum()

10

In [141]:
a.mean()

2.5

In [142]:
a.std()

1.118033988749895

In [120]:
a.var()

1.25

In [134]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [122]:
A.sum() #statistical calculation of the matrice

45

In [123]:
A.mean()

5.0

In [124]:
A.std()

2.581988897471611

In [125]:
A.var()

6.666666666666667

In [136]:
A.sum(axis = 0) # the sum per axis of c1, c2, c3

array([12, 15, 18])

In [135]:
A.sum(axis = 1) # the sum per axis of r1,r2 and r3

array([ 6, 15, 24])

In [137]:
a

array([1, 2, 3, 4])

In [138]:
a = np.arange(4)

AttributeError: module 'numpy' has no attribute 'arrange'

In [139]:
a

array([1, 2, 3, 4])

In [143]:
a = np.arange(4)

AttributeError: module 'numpy' has no attribute 'arrange'

In [144]:
a = np.array(4)

In [145]:
a

array(4)

In [146]:
a = np.arange(4)

In [147]:
a

array([0, 1, 2, 3])

In [149]:
a = np.arange(6)

In [150]:
a

array([0, 1, 2, 3, 4, 5])

In [151]:
a = np.arange(4) #basic array

In [152]:
a

array([0, 1, 2, 3])

In [153]:
a + 10 #example of a vectorized operation with an array and scalar (arithmetic operation)

array([10, 11, 12, 13])

In [154]:
a * 10 #example of a vectorized operation with an array and scalar

array([ 0, 10, 20, 30])

In [155]:
a

array([0, 1, 2, 3])

In [169]:
a += 100 #this is an example of a modification
         #+= adds another value with the variable's value and assigns the new value to the variable - in this case were making broadcast operation
         # and adding 100 to each one of the elements in the array

In [157]:
a #a hasn't returned thus has been modified - immutable object has changed

array([100, 101, 102, 103])

In [158]:
l = [0, 1, 2, 3] #python script thats a correspondence of vectorized operations are list comprehensions --

In [159]:
[i * 10 for i in l] #python script -- thats expressing an operation for each one of the element. NumPy's version is extremely optimized and fast

[0, 10, 20, 30]

In [160]:
a = np.arange(4)

In [161]:
a

array([0, 1, 2, 3])

In [166]:
b = np.array([10, 10, 10, 10])

In [167]:
a + b

array([10, 11, 12, 13])

In [168]:
a*b

array([ 0, 10, 20, 30])

In [173]:
a = np.arange(5)

In [174]:
a

array([0, 1, 2, 3, 4])

In [175]:
a + 20

array([20, 21, 22, 23, 24])

In [176]:
a

array([0, 1, 2, 3, 4])

In [177]:
a[[0,-1]] #NumPy method (multi indexing)

array([0, 4])

In [178]:
a[0], a[2] #traditional python method

(0, 2)

In [180]:
a[[True, False, False, True, False]] #boolean method the result of broadcasting Boolean operations

array([0, 3])

In [181]:
 a >= 2 # a is greater than and equal to 2

array([False, False,  True,  True,  True])

In [182]:
a[a>=2] #combining boolean and multiindexing - index of operation - this is a query method looking up the data and saying give me all the elements that match the condition.
        #This was done by coonstructing a predicate [181]

array([2, 3, 4])

In [183]:
a.mean()

2.0

In [184]:
a[ a > a.mean()] # give all the elements that are greater than the mean

array([3, 4])

In [186]:
a[~(a > a.mean())] #give all the elements that are not greater than the mean

array([0, 1, 2])

In [187]:
a[(a == 0) | (a ==1)] #boolean operator of 'or'

array([0, 1])

In [188]:
a[(a <= 2) & (a % 2 == 0)]#boolean operator of 'and'

array([0, 2])

In [189]:
A = np.random.randint(100, size=(3,3)) #random matrix constructed

In [190]:
A

array([[47, 86, 77],
       [12, 89,  3],
       [30, 66, 68]])

In [192]:
A [np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]                       # WE NEVER DO THIS WE JUST RUN QUERY FILTERING OPTION

array([47, 77, 89, 30, 68])

In [193]:
A > 30 #Query filtering

array([[ True,  True,  True],
       [False,  True, False],
       [False,  True,  True]])

In [ ]:
A[A>30]

In [194]:
a = np.arange(5)

In [195]:
a <= 3

array([ True,  True,  True,  True, False])

In [196]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [197]:
B = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [204]:
A.dot(B) # Matrix - Dot product - multiplying both matrices

array([[20, 14],
       [56, 41],
       [92, 68]])

In [205]:
A @ B #cross product - determinant 

array([[20, 14],
       [56, 41],
       [92, 68]])

In [206]:
B.T #Transposing matrices - changing the rows into columns

array([[6, 4, 2],
       [5, 3, 1]])

In [201]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [202]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [207]:
sys.getsizeof(1) #size of int in python

28

In [208]:
np.dtype(np.int8).itemsize #size of int in NumPY

1

In [209]:
np.dtype(float).itemsize

8

In [220]:
l = list(range(1000)) #python list that has the first 1000 numbers

In [222]:
%time sum([x **2 for x in l]) #python performance test - in this case --
                              #-- squaring all the elements in the list and suming it

CPU times: total: 0 ns
Wall time: 999 µs


332833500

In [217]:
a = np.arange(1000) #NumPy array 

In [223]:
%time np.sum(a ** 2) #NumPy performance test

CPU times: total: 0 ns
Wall time: 0 ns


332833500